name: E2E Test - vSphere Management and Workload Cluster Go Lang

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - release-*
    paths:
      - "**.go"
      - ".github/workflows/e2e-vsphere-management-and-workload-cluster.yaml"
    tags-ignore:
      - "**"

jobs:
  e2e-vsphere-management-cluster-test:
    name: E2E vSphere Management and Workload Cluster Test
    # Only run this job if we're in the main repo, not a fork.
    if: github.repository == 'karuppiah7890/tce-e2e-test'
    runs-on: vsphere-e2e-runner
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: "1.17"
        id: go

      - name: Check out code
        uses: actions/checkout@v1

      - name: Get Date
        id: get-date
        shell: bash
        run: |
          echo "::set-output name=date::$(date -u "+%Y-%m")"

      - name: Restore Go Cache
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ steps.get-date.outputs.date }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Run vSphere Management and Workload Cluster E2E Test
        env:
          DAILY_BUILD: ${{ github.event.client_payload.daily-build }}
          VSPHERE_MANAGEMENT_CLUSTER_ENDPOINT: ${{ secrets.VSPHERE_MANAGEMENT_CLUSTER_ENDPOINT }}
          VSPHERE_WORKLOAD_CLUSTER_ENDPOINT: ${{ secrets.VSPHERE_WORKLOAD_CLUSTER_ENDPOINT }}
          VSPHERE_SERVER: ${{ secrets.VSPHERE_SERVER }}
          VSPHERE_SSH_AUTHORIZED_KEY: ${{ secrets.VSPHERE_SSH_AUTHORIZED_KEY }}
          VSPHERE_USERNAME: ${{ secrets.VSPHERE_USERNAME }}
          VSPHERE_PASSWORD: ${{ secrets.VSPHERE_PASSWORD }}
          VSPHERE_DATACENTER: ${{ secrets.VSPHERE_DATACENTER }}
          VSPHERE_DATASTORE: ${{ secrets.VSPHERE_DATASTORE }}
          VSPHERE_FOLDER: ${{ secrets.VSPHERE_FOLDER }}
          VSPHERE_NETWORK: ${{ secrets.VSPHERE_NETWORK }}
          VSPHERE_RESOURCE_POOL: ${{ secrets.VSPHERE_RESOURCE_POOL }}
        run: |
          go test -v ./vsphere_test.go --timeout=2h 

      - name: Collect tanzu diagnostics data
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: diagnostics-data
          path: |
            bootstrap.*.diagnostics.tar.gz
            management-cluster.*.diagnostics.tar.gz
            workload-cluster.*.diagnostics.tar.gz
